### PR TITLE
arm-tv

### PR DESCRIPTION
**Pull request by tanmaytirpankar**

### CODE REVIEW

**Comment by regehr** [comment]
looks great overall but please add test cases!!!

**Comment by tanmaytirpankar** [comment]
Bug was introduced by me when I added code for PC-relative addressing. Bug does not show up in optimized LLVM IR. Only way I can think of revealing the bug is by creating a test case that would fail after the bug-fix. If there is no way to add such a test case for Alive, the PR can be merged.

**Comment by regehr** [comment]
currently, this branch is setup so my large number of auto-generated vector test cases aren't running. if some of those test cases are ones that test your new code, then I agree you can avoid writing test cases of your own, but you do need to move them into a place where they're going to actually run. try to find a maximal set of them to move over. we can move the rest later as we finish adding memory+vector instructions.

**Comment by tanmaytirpankar** [comment]
I have moved the unhandled tests within a subdirectory and changed lit.cfg.py to exclude it. I will move tests out as they are handled.

**Comment by regehr** [comment]
excellent-- thanks Tanmay!!

**Pull request merged**
